version: "3.8"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    # environment:
    #   DB_HOST: db
    #   DB_USER: postgres
    #   DB_PASSWORD: password
    #   DB_NAME: print_service
    # depends_on:
    #   - db
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "8082:8080"
#
#   db:
#     image: postgres:15
#     container_name: postgres
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: print_service
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#
# volumes:
#   postgres_data:
